/* Import guidance data from the ClassCodex addon.
 *
 * ClassCodex (MIT, jfstn, https://www.curseforge.com/wow/addons/class-codex)
 * ships hand-aggregated guidance from Wowhead, Icy Veins, Archon and Murlok as
 * plain Lua tables. That is a far better source than scraping any of those
 * sites ourselves, and its `sources.lua` carries per-spec attribution URLs.
 *
 * TWO SAFETY RULES, both non-negotiable:
 *
 * 1. THE ADDON DIRECTORY IS READ-ONLY. It arrives over Syncthing configured
 *    `sendreceive`, so anything written there propagates back to the PC and
 *    could corrupt a live addon install. This module only ever reads.
 * 2. WE SNAPSHOT, WE DO NOT READ LIVE. Request handling must never touch the
 *    sync path: a sync in flight can be observed half-written. Import produces
 *    a normalised snapshot stamped with the addon version and scrape date, and
 *    everything downstream reads that.
 *
 * The data is machine-generated by the addon's own scraper, so it is regular
 * enough for a small Lua table-literal parser. That is deliberately not a
 * general Lua interpreter: it understands table constructors, strings,
 * numbers, booleans and nil, which is all these files contain.
 */

import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

export const CLASSCODEX_LICENCE = 'MIT — Copyright (c) 2026 jfstn';
export const DEFAULT_ADDON_PATH = '/classcodex';

/** Parse a Lua table literal. Returns a JS value; throws on anything exotic. */
export function parseLuaTable(source, startIndex = 0) {
  let index = startIndex;

  const skipTrivia = () => {
    for (;;) {
      while (index < source.length && /\s/.test(source[index])) index += 1;
      if (source.startsWith('--', index)) {
        const newline = source.indexOf('\n', index);
        index = newline === -1 ? source.length : newline + 1;
        continue;
      }
      break;
    }
  };

  const readString = () => {
    const quote = source[index];
    index += 1;
    let value = '';
    while (index < source.length && source[index] !== quote) {
      if (source[index] === '\\') {
        const next = source[index + 1];
        value += next === 'n' ? '\n' : next === 't' ? '\t' : next;
        index += 2;
        continue;
      }
      value += source[index];
      index += 1;
    }
    index += 1;
    return value;
  };

  const readValue = () => {
    skipTrivia();
    const character = source[index];
    if (character === '{') return readTable();
    if (character === '"' || character === "'") return readString();

    const rest = source.slice(index);
    const literal = /^(true|false|nil)\b/.exec(rest);
    if (literal) {
      index += literal[0].length;
      return literal[0] === 'true' ? true : literal[0] === 'false' ? false : null;
    }
    const number = /^-?\d+(\.\d+)?/.exec(rest);
    if (number) {
      index += number[0].length;
      return Number(number[0]);
    }
    // An identifier (a reference to another table). Not resolvable here.
    const identifier = /^[A-Za-z_][\w.]*/.exec(rest);
    if (identifier) {
      index += identifier[0].length;
      return null;
    }
    throw new SyntaxError(`Unparseable Lua value at ${index}: ${rest.slice(0, 40)}`);
  };

  function readTable() {
    index += 1; // consume {
    const array = [];
    const record = {};
    let hasKeys = false;

    for (;;) {
      skipTrivia();
      if (source[index] === '}') { index += 1; break; }
      if (index >= source.length) throw new SyntaxError('Unterminated Lua table');

      let key = null;
      if (source[index] === '[') {
        index += 1;
        key = readValue();
        skipTrivia();
        index += 1; // consume ]
        skipTrivia();
        index += 1; // consume =
      } else {
        const identifier = /^([A-Za-z_]\w*)\s*=(?!=)/.exec(source.slice(index));
        if (identifier) {
          key = identifier[1];
          index += identifier[0].length;
        }
      }

      const value = readValue();
      if (key === null) array.push(value);
      else { record[key] = value; hasKeys = true; }

      skipTrivia();
      if (source[index] === ',' || source[index] === ';') index += 1;
    }

    if (hasKeys && array.length > 0) return { ...record, entries: array };
    return hasKeys ? record : array;
  }

  skipTrivia();
  return readValue();
}

/** Pull one assigned global table out of a ClassCodex data file. */
export function extractAssignment(source, globalName) {
  const marker = new RegExp(`${globalName}\\s*\\[\\s*"([A-Z_]+)"\\s*\\]\\s*=\\s*\\{`);
  const match = marker.exec(source);
  if (!match) return null;
  const braceIndex = source.indexOf('{', match.index);
  return { classToken: match[1], value: parseLuaTable(source, braceIndex) };
}

const FILES = Object.freeze({
  guide: { file: 'guide.lua', global: 'ClassCodexData' },
  sources: { file: 'sources.lua', global: 'ClassCodexSources' },
  gearWowhead: { file: 'gear-wowhead.lua', global: 'ClassCodexGearData' },
  gearArchon: { file: 'gear-archon.lua', global: 'ClassCodexArchonGearData' },
  gearIcyVeins: { file: 'gear-icyveins.lua', global: 'ClassCodexIcyVeinsData' },
  talentsIcyVeins: { file: 'talents-icyveins.lua', global: 'ClassCodexIcyVeinsTalentData' },
  archonStats: { file: 'archon-stats.lua', global: 'ClassCodexArchonStats' },
  archonTalents: { file: 'archon-talents.lua', global: 'ClassCodexArchonData' },
  crafting: { file: 'crafting.lua', global: 'ClassCodexCraftingData' }
});

/**
 * Read the addon and produce a normalised snapshot.
 *
 * `addonPath` must point at a read-only copy of the addon directory.
 */
export async function importClassCodex(addonPath = DEFAULT_ADDON_PATH) {
  const toc = await readFile(join(addonPath, 'ClassCodex.toc'), 'utf8').catch(() => '');
  const version = /^##\s*Version:\s*(.+)$/m.exec(toc)?.[1]?.trim() || null;
  const interfaceVersion = /^##\s*Interface:\s*(.+)$/m.exec(toc)?.[1]?.trim() || null;

  const generated = await readFile(join(addonPath, 'Data', 'Generated.lua'), 'utf8').catch(() => '');
  const lastScrape = /ClassCodex_LastScrape\s*=\s*"([^"]+)"/.exec(generated)?.[1] || null;

  const dataDir = join(addonPath, 'Data');
  const classDirs = (await readdir(dataDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  const specs = {};
  for (const classDir of classDirs) {
    for (const [key, definition] of Object.entries(FILES)) {
      const source = await readFile(join(dataDir, classDir, definition.file), 'utf8').catch(() => null);
      if (!source) continue;
      let extracted;
      try {
        extracted = extractAssignment(source, definition.global);
      } catch {
        continue; // A single unparseable file must not fail the whole import.
      }
      if (!extracted) continue;

      for (const [specKey, specValue] of Object.entries(extracted.value || {})) {
        const id = `${extracted.classToken}/${specKey}`;
        specs[id] = specs[id] || { classToken: extracted.classToken, spec: specKey };
        specs[id][key] = specValue;
      }
    }
  }

  return {
    provenance: 'community',
    source: 'classcodex',
    addonVersion: version,
    interfaceVersion,
    lastScrape,
    licence: CLASSCODEX_LICENCE,
    importedFrom: addonPath,
    specCount: Object.keys(specs).length,
    specs
  };
}

/** One spec's guidance, with attribution and staleness attached. */
export function specGuidance(snapshot, classToken, spec) {
  const entry = snapshot?.specs?.[`${classToken.toUpperCase()}/${spec.toLowerCase()}`];
  if (!entry) return null;
  return {
    provenance: 'community',
    source: 'classcodex',
    addonVersion: snapshot.addonVersion,
    lastScrape: snapshot.lastScrape,
    licence: snapshot.licence,
    class: entry.classToken,
    spec: entry.spec,
    statPriorities: entry.guide?.priorities ?? null,
    statTargets: entry.archonStats ?? null,
    talentBuilds: entry.guide?.talents ?? null,
    rotation: entry.guide?.rotation ?? null,
    trinkets: entry.gearWowhead?.trinkets ?? null,
    enchants: entry.gearWowhead?.enchants ?? null,
    gems: entry.gearWowhead?.gems ?? null,
    consumables: entry.gearWowhead?.consumables ?? null,
    bisGear: {
      wowhead: entry.gearWowhead?.bisGear ?? null,
      archon: entry.gearArchon?.bisGear ?? null,
      icyVeins: entry.gearIcyVeins?.bisGear ?? null
    },
    crafting: entry.crafting ?? null,
    sourceUrls: entry.sources ?? null
  };
}
